# Generated by Django 4.1.1 on 2022-10-06 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(max_length=5000, verbose_name='Описание')),
                ('is_new', models.BooleanField(verbose_name='Состояние')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Цена')),
                ('phone_1', models.CharField(blank=True, max_length=30, null=True, verbose_name='Телефон')),
                ('phone_2', models.CharField(blank=True, max_length=30, null=True, verbose_name='Телефон')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания или обновления')),
                ('moderation', models.BooleanField(default=False, verbose_name='Модерация')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='url')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания или обновления')),
                ('slug', models.SlugField(unique=True, verbose_name='url')),
                ('advert', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='advertisements.advert', verbose_name='Объявление')),
            ],
            options={
                'verbose_name': 'Галерея',
                'verbose_name_plural': 'Галереи',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='url')),
            ],
            options={
                'verbose_name': 'Область',
                'verbose_name_plural': 'Области',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50, unique=True, verbose_name='Город/район')),
                ('slug', models.SlugField(unique=True, verbose_name='url')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertisements.region', verbose_name='Область')),
            ],
            options={
                'verbose_name': 'Город/район',
                'verbose_name_plural': 'Города/районы',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('image', models.ImageField(upload_to='advertisements/<django.db.models.fields.related.ForeignKey>', verbose_name='Фото')),
                ('slug', models.SlugField(unique=True, verbose_name='url')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertisements.gallery', verbose_name='Галерея')),
            ],
            options={
                'verbose_name': 'Фотография',
                'verbose_name_plural': 'Фотографии',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='url')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='advertisements.category', verbose_name='Родитель')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='advert',
            name='category',
            field=mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertisements.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='advert',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertisements.place', verbose_name='Местоположение'),
        ),
        migrations.AddField(
            model_name='advert',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
