# Generated by Django 4.1.1 on 2022-10-12 12:58

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0003_alter_category_options_alter_place_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='value',
            options={'ordering': ('characteristic', 'id'), 'verbose_name': 'Значение', 'verbose_name_plural': 'Значения характеристик'},
        ),
        migrations.RemoveField(
            model_name='characteristic',
            name='poss_values',
        ),
        migrations.AddField(
            model_name='advert',
            name='charvalues',
            field=smart_selects.db_fields.ChainedManyToManyField(auto_choose=True, chained_field='category', chained_model_field='characteristic__categories', horizontal=True, to='advertisements.value', verbose_name='Значения характеристик'),
        ),
        migrations.AddField(
            model_name='advert',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='adverts', to='advertisements.region', verbose_name='Регион'),
        ),
        migrations.AddField(
            model_name='value',
            name='characteristic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='values', to='advertisements.characteristic', verbose_name='Характеристика'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='category',
            field=mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adverts', to='advertisements.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='advert',
            name='place',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='region', chained_model_field='region', on_delete=django.db.models.deletion.CASCADE, related_name='adverts', show_all=True, to='advertisements.place', verbose_name='Местоположение'),
        ),
        migrations.AlterField(
            model_name='category',
            name='full_name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Полное название'),
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='full_name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Полное наименование'),
        ),
        migrations.DeleteModel(
            name='AdvertCharValue',
        ),
    ]
